### ISSUE TITLE
Tab to complete not working beyond current folder

### ISSUE THREAD

**Issue by velvetshoehorn** [lkytal/BuiltinCmd#2]
Nice extension, but I think I found an issue. If I have this structure:
C:\Root\First\Second\Third\File.ext
And I'm in the Root folder, I can type:
**cd F[tab]**

and get:
**cd First**

Then, if I:
**cd First\S[tab]**

It finds the "Second" folder but changes the command to:
**cd Second**

Instead of:
**cd First\Second**

At least that's what happens in VS 2015 Community running on Windows 7... for me. :-)

**Comment by Breakthrough** [comment]
I'm also having an issue on Visual Studio 2013 where the tab-command autocomplete seems to not function whatsoever.

Do you have any suggestions?  I tried to look for any options I can set to enable it, but can find nothing...

(P.S. Great project, by the way, loving how it integrates just like the Ctrl+` shortcut terminal in VSCode.  Would just love it even more if I could figure out how to get this autocomplete working :)

**Comment by lkytal** [comment]
@jcarlow  I've upload version 1.7.1 which should have fixed those problems.

@Breakthrough  Works fine with vs2013 on my computer. what's your system?

**Comment by velvetshoehorn** [comment]
Awesome! Works great for me. Nice work, and quick too! Thanks.
