### ISSUE TITLE
Can't open it

### ISSUE THREAD

**Issue by schwarcu** [lkytal/BuiltinCmd#5]
How do I open this window after it's installed?

**Comment by lkytal** [comment]
You can open it via "view -> other window -> Toggle BuiltinCmd" or just press `Ctrl + Shift + T` to show it.

**Comment by schwarcu** [comment]
Thank you it worked.
Btw, is it possible to switch to powershell or bash? or is there identical extension for bash/powershell?
I'm sorry for asking such trivial questions but haven't worked in VS for ages.

**Comment by lkytal** [comment]
I planned to support powershell afterwards, you may just run powershell inside current terminal, although some features may not work correctly.
