### ISSUE TITLE
Ability to specify startup arguments

### ISSUE THREAD

**Issue by webmaster442** [lkytal/BuiltinCmd#7]
Are you planning to support startup arguments?

I would like to start a bach file when starting the terminal. 

Usually I do this with cmd.exe /K mybach.cmd, but unfortunately it's not yet possible with builtinCmd

**Comment by lkytal** [comment]
You shall find options for global and project-wise startup commands within the setting.

![b](https://user-images.githubusercontent.com/3395795/38703141-6c0d9170-3e70-11e8-9c22-1317c456563a.png)

**Comment by webmaster442** [comment]
Thanks
